INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (1, 'Afghanistan', 4, '93', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (2, 'Aland Islands', 248, '358-18', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (3, 'Albania', 8, '355', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (4, 'Algeria', 12, '213', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (5, 'American Samoa', 16, '1-684', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (6, 'Andorra', 20, '376', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (7, 'Angola', 24, '244', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (8, 'Anguilla', 660, '1-264', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (9, 'Antarctica', 10, '672', 'Polar', 6, '', NULL);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (10, 'Antigua and Barbuda', 28, '1-268', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (11, 'Argentina', 32, '54', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (12, 'Armenia', 51, '374', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (13, 'Aruba', 533, '297', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (14, 'Australia', 36, '61', 'Oceania', 5, 'Australia and New Zealand', 19);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (15, 'Austria', 40, '43', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (16, 'Azerbaijan', 31, '994', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (17, 'The Bahamas', 44, '1-242', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (18, 'Bahrain', 48, '973', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (19, 'Bangladesh', 50, '880', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (20, 'Barbados', 52, '1-246', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (21, 'Belarus', 112, '375', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (22, 'Belgium', 56, '32', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (23, 'Belize', 84, '501', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (24, 'Benin', 204, '229', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (25, 'Bermuda', 60, '1-441', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (26, 'Bhutan', 64, '975', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (27, 'Bolivia', 68, '591', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (28, 'Bosnia and Herzegovina', 70, '387', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (29, 'Botswana', 72, '267', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (30, 'Bouvet Island', 74, '0055', '', NULL, '', NULL);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (31, 'Brazil', 76, '55', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (32, 'British Indian Ocean Territory', 86, '246', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (33, 'Brunei', 96, '673', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (34, 'Bulgaria', 100, '359', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (35, 'Burkina Faso', 854, '226', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (36, 'Burundi', 108, '257', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (37, 'Cambodia', 116, '855', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (38, 'Cameroon', 120, '237', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (39, 'Canada', 124, '1', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (40, 'Cape Verde', 132, '238', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (41, 'Cayman Islands', 136, '1-345', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (42, 'Central African Republic', 140, '236', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (43, 'Chad', 148, '235', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (44, 'Chile', 152, '56', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (45, 'China', 156, '86', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (46, 'Christmas Island', 162, '61', 'Oceania', 5, 'Australia and New Zealand', 19);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (47, 'Cocos (Keeling) Islands', 166, '61', 'Oceania', 5, 'Australia and New Zealand', 19);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (48, 'Colombia', 170, '57', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (49, 'Comoros', 174, '269', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (50, 'Congo', 178, '242', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (51, 'Democratic Republic of the Congo', 180, '243', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (52, 'Cook Islands', 184, '682', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (53, 'Costa Rica', 188, '506', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (54, 'Cote D''Ivoire (Ivory Coast)', 384, '225', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (55, 'Croatia', 191, '385', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (56, 'Cuba', 192, '53', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (57, 'Cyprus', 196, '357', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (58, 'Czech Republic', 203, '420', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (59, 'Denmark', 208, '45', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (60, 'Djibouti', 262, '253', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (61, 'Dominica', 212, '1-767', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (62, 'Dominican Republic', 214, '1-809 and 1-829', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (63, 'Timor-Leste', 626, '670', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (64, 'Ecuador', 218, '593', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (65, 'Egypt', 818, '20', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (66, 'El Salvador', 222, '503', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (67, 'Equatorial Guinea', 226, '240', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (68, 'Eritrea', 232, '291', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (69, 'Estonia', 233, '372', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (70, 'Ethiopia', 231, '251', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (71, 'Falkland Islands', 238, '500', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (72, 'Faroe Islands', 234, '298', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (73, 'Fiji Islands', 242, '679', 'Oceania', 5, 'Melanesia', 20);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (74, 'Finland', 246, '358', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (75, 'France', 250, '33', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (76, 'French Guiana', 254, '594', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (77, 'French Polynesia', 258, '689', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (78, 'French Southern Territories', 260, '262', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (79, 'Gabon', 266, '241', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (80, 'Gambia The', 270, '220', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (81, 'Georgia', 268, '995', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (82, 'Germany', 276, '49', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (83, 'Ghana', 288, '233', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (84, 'Gibraltar', 292, '350', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (85, 'Greece', 300, '30', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (86, 'Greenland', 304, '299', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (87, 'Grenada', 308, '1-473', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (88, 'Guadeloupe', 312, '590', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (89, 'Guam', 316, '1-671', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (90, 'Guatemala', 320, '502', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (91, 'Guernsey and Alderney', 831, '44-1481', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (92, 'Guinea', 324, '224', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (93, 'Guinea-Bissau', 624, '245', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (94, 'Guyana', 328, '592', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (95, 'Haiti', 332, '509', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (96, 'Heard Island and McDonald Islands', 334, '672', '', NULL, '', NULL);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (97, 'Honduras', 340, '504', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (98, 'Hong Kong S.A.R.', 344, '852', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (99, 'Hungary', 348, '36', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (100, 'Iceland', 352, '354', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (101, 'India', 356, '91', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (102, 'Indonesia', 360, '62', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (103, 'Iran', 364, '98', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (104, 'Iraq', 368, '964', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (105, 'Ireland', 372, '353', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (106, 'Israel', 376, '972', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (107, 'Italy', 380, '39', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (108, 'Jamaica', 388, '1-876', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (109, 'Japan', 392, '81', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (110, 'Jersey', 832, '44-1534', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (111, 'Jordan', 400, '962', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (112, 'Kazakhstan', 398, '7', 'Asia', 3, 'Central Asia', 10);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (113, 'Kenya', 404, '254', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (114, 'Kiribati', 296, '686', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (115, 'North Korea', 408, '850', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (116, 'South Korea', 410, '82', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (117, 'Kuwait', 414, '965', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (118, 'Kyrgyzstan', 417, '996', 'Asia', 3, 'Central Asia', 10);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (119, 'Laos', 418, '856', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (120, 'Latvia', 428, '371', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (121, 'Lebanon', 422, '961', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (122, 'Lesotho', 426, '266', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (123, 'Liberia', 430, '231', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (124, 'Libya', 434, '218', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (125, 'Liechtenstein', 438, '423', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (126, 'Lithuania', 440, '370', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (127, 'Luxembourg', 442, '352', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (128, 'Macau S.A.R.', 446, '853', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (129, 'North Macedonia', 807, '389', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (130, 'Madagascar', 450, '261', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (131, 'Malawi', 454, '265', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (132, 'Malaysia', 458, '60', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (133, 'Maldives', 462, '960', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (134, 'Mali', 466, '223', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (135, 'Malta', 470, '356', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (136, 'Man (Isle of)', 833, '44-1624', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (137, 'Marshall Islands', 584, '692', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (138, 'Martinique', 474, '596', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (139, 'Mauritania', 478, '222', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (140, 'Mauritius', 480, '230', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (141, 'Mayotte', 175, '262', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (142, 'Mexico', 484, '52', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (143, 'Micronesia', 583, '691', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (144, 'Moldova', 498, '373', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (145, 'Monaco', 492, '377', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (146, 'Mongolia', 496, '976', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (147, 'Montenegro', 499, '382', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (148, 'Montserrat', 500, '1-664', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (149, 'Morocco', 504, '212', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (150, 'Mozambique', 508, '258', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (151, 'Myanmar', 104, '95', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (152, 'Namibia', 516, '264', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (153, 'Nauru', 520, '674', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (154, 'Nepal', 524, '977', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (155, 'Bonaire, Sint Eustatius and Saba', 535, '599', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (156, 'Netherlands', 528, '31', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (157, 'New Caledonia', 540, '687', 'Oceania', 5, 'Melanesia', 20);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (158, 'New Zealand', 554, '64', 'Oceania', 5, 'Australia and New Zealand', 19);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (159, 'Nicaragua', 558, '505', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (160, 'Niger', 562, '227', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (161, 'Nigeria', 566, '234', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (162, 'Niue', 570, '683', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (163, 'Norfolk Island', 574, '672', 'Oceania', 5, 'Australia and New Zealand', 19);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (164, 'Northern Mariana Islands', 580, '1-670', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (165, 'Norway', 578, '47', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (166, 'Oman', 512, '968', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (167, 'Pakistan', 586, '92', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (168, 'Palau', 585, '680', 'Oceania', 5, 'Micronesia', 21);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (169, 'Palestinian Territory Occupied', 275, '970', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (170, 'Panama', 591, '507', 'Americas', 2, 'Central America', 9);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (171, 'Papua New Guinea', 598, '675', 'Oceania', 5, 'Melanesia', 20);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (172, 'Paraguay', 600, '595', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (173, 'Peru', 604, '51', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (174, 'Philippines', 608, '63', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (175, 'Pitcairn Island', 612, '870', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (176, 'Poland', 616, '48', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (177, 'Portugal', 620, '351', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (178, 'Puerto Rico', 630, '1-787 and 1-939', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (179, 'Qatar', 634, '974', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (180, 'Reunion', 638, '262', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (181, 'Romania', 642, '40', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (182, 'Russia', 643, '7', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (183, 'Rwanda', 646, '250', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (184, 'Saint Helena', 654, '290', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (185, 'Saint Kitts and Nevis', 659, '1-869', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (186, 'Saint Lucia', 662, '1-758', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (187, 'Saint Pierre and Miquelon', 666, '508', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (188, 'Saint Vincent and the Grenadines', 670, '1-784', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (189, 'Saint-Barthelemy', 652, '590', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (190, 'Saint-Martin (French part)', 663, '590', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (191, 'Samoa', 882, '685', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (192, 'San Marino', 674, '378', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (193, 'Sao Tome and Principe', 678, '239', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (194, 'Saudi Arabia', 682, '966', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (195, 'Senegal', 686, '221', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (196, 'Serbia', 688, '381', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (197, 'Seychelles', 690, '248', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (198, 'Sierra Leone', 694, '232', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (199, 'Singapore', 702, '65', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (200, 'Slovakia', 703, '421', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (201, 'Slovenia', 705, '386', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (202, 'Solomon Islands', 90, '677', 'Oceania', 5, 'Melanesia', 20);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (203, 'Somalia', 706, '252', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (204, 'South Africa', 710, '27', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (205, 'South Georgia', 239, '500', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (206, 'South Sudan', 728, '211', 'Africa', 1, 'Middle Africa', 2);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (207, 'Spain', 724, '34', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (208, 'Sri Lanka', 144, '94', 'Asia', 3, 'Southern Asia', 14);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (209, 'Sudan', 729, '249', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (210, 'Suriname', 740, '597', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (211, 'Svalbard and Jan Mayen Islands', 744, '47', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (212, 'Eswatini', 748, '268', 'Africa', 1, 'Southern Africa', 5);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (213, 'Sweden', 752, '46', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (214, 'Switzerland', 756, '41', 'Europe', 4, 'Western Europe', 17);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (215, 'Syria', 760, '963', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (216, 'Taiwan', 158, '886', 'Asia', 3, 'Eastern Asia', 12);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (217, 'Tajikistan', 762, '992', 'Asia', 3, 'Central Asia', 10);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (218, 'Tanzania', 834, '255', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (219, 'Thailand', 764, '66', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (220, 'Togo', 768, '228', 'Africa', 1, 'Western Africa', 3);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (221, 'Tokelau', 772, '690', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (222, 'Tonga', 776, '676', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (223, 'Trinidad and Tobago', 780, '1-868', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (224, 'Tunisia', 788, '216', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (225, 'Turkey', 792, '90', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (226, 'Turkmenistan', 795, '993', 'Asia', 3, 'Central Asia', 10);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (227, 'Turks and Caicos Islands', 796, '1-649', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (228, 'Tuvalu', 798, '688', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (229, 'Uganda', 800, '256', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (230, 'Ukraine', 804, '380', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (231, 'United Arab Emirates', 784, '971', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (232, 'United Kingdom', 826, '44', 'Europe', 4, 'Northern Europe', 18);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (233, 'United States', 840, '1', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (234, 'United States Minor Outlying Islands', 581, '1', 'Americas', 2, 'Northern America', 6);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (235, 'Uruguay', 858, '598', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (236, 'Uzbekistan', 860, '998', 'Asia', 3, 'Central Asia', 10);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (237, 'Vanuatu', 548, '678', 'Oceania', 5, 'Melanesia', 20);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (238, 'Vatican City State (Holy See)', 336, '379', 'Europe', 4, 'Southern Europe', 16);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (239, 'Venezuela', 862, '58', 'Americas', 2, 'South America', 8);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (240, 'Vietnam', 704, '84', 'Asia', 3, 'South-Eastern Asia', 13);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (241, 'Virgin Islands (British)', 92, '1-284', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (242, 'Virgin Islands (US)', 850, '1-340', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (243, 'Wallis and Futuna Islands', 876, '681', 'Oceania', 5, 'Polynesia', 22);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (244, 'Western Sahara', 732, '212', 'Africa', 1, 'Northern Africa', 1);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (245, 'Yemen', 887, '967', 'Asia', 3, 'Western Asia', 11);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (246, 'Zambia', 894, '260', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (247, 'Zimbabwe', 716, '263', 'Africa', 1, 'Eastern Africa', 4);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (248, 'Kosovo', 926, '383', 'Europe', 4, 'Eastern Europe', 15);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (249, 'Curaçao', 531, '599', 'Americas', 2, 'Caribbean', 7);
INSERT INTO "um_country" ("id", "name", "numeric_code", "phonecode", "region", "region_id", "subregion", "subregion_id") VALUES (250, 'Sint Maarten (Dutch part)', 534, '1721', 'Americas', 2, 'Caribbean', 7);
