INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (1, 'Northern Africa', 1);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (2, 'Middle Africa', 1);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (3, 'Western Africa', 1);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (4, 'Eastern Africa', 1);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (5, 'Southern Africa', 1);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (6, 'Northern America', 2);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (7, 'Caribbean', 2);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (8, 'South America', 2);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (9, 'Central America', 2);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (10, 'Central Asia', 3);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (11, 'Western Asia', 3);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (12, 'Eastern Asia', 3);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (13, 'South-Eastern Asia', 3);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (14, 'Southern Asia', 3);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (15, 'Eastern Europe', 4);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (16, 'Southern Europe', 4);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (17, 'Western Europe', 4);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (18, 'Northern Europe', 4);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (19, 'Australia and New Zealand', 5);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (20, 'Melanesia', 5);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (21, 'Micronesia', 5);
INSERT INTO "um_subregion" ("id", "name", "region_id") VALUES (22, 'Polynesia', 5);
